import { ExperimentStep } from './labTrainingSystem';

export const distillationExperiment: ExperimentStep[] = [
  {
    id: 'distillation-1',
    title: 'Safety Check',
    description: 'Put on safety goggles, lab coat, and gloves before starting the distillation.',
    required: true,
    completed: false,
    safetyCheck: true,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
    fumeHoodRequired: false,
    equipmentRequired: ['Safety goggles', 'Lab coat', 'Gloves'],
  },
  {
    id: 'distillation-2',
    title: 'Set Up Distillation Apparatus',
    description: 'Assemble the distillation setup: round-bottom flask on heating mantle, condenser attached, and receiving flask positioned.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
    fumeHoodRequired: false,
    equipmentRequired: ['Round-bottom flask', 'Condenser', 'Receiving flask', 'Heating mantle'],
  },
  {
    id: 'distillation-3',
    title: 'Add Liquid Mixture',
    description: 'Pour the liquid mixture (e.g., water and ethanol) into the round-bottom flask. Fill to about 2/3 capacity. Add boiling chips to prevent bumping.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
    fumeHoodRequired: false,
    equipmentRequired: ['Round-bottom flask', 'Liquid mixture', 'Boiling chips'],
  },
  {
    id: 'distillation-4',
    title: 'Start Cooling Water',
    description: 'Turn on the cooling water to the condenser. Water should flow from bottom to top. Ensure steady flow.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
    fumeHoodRequired: false,
    equipmentRequired: ['Condenser', 'Cooling water'],
  },
  {
    id: 'distillation-5',
    title: 'Begin Heating',
    description: 'Turn on the heating mantle or Bunsen burner. Heat gently and gradually. Monitor the temperature using the thermometer.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
    fumeHoodRequired: false,
    equipmentRequired: ['Heating mantle', 'Thermometer'],
  },
  {
    id: 'distillation-6',
    title: 'Observe Boiling',
    description: 'Watch for the liquid to start boiling. Note the temperature when the first drops of distillate appear. This is the boiling point of the first component.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
    fumeHoodRequired: false,
    equipmentRequired: ['Thermometer'],
  },
  {
    id: 'distillation-7',
    title: 'Collect Distillate',
    description: 'Collect the distillate in the receiving flask. Monitor the temperature range. Collect fractions at different temperature ranges if needed.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
    fumeHoodRequired: false,
    equipmentRequired: ['Receiving flask', 'Thermometer'],
  },
  {
    id: 'distillation-8',
    title: 'Record Observations',
    description: 'Record the volume of distillate collected, boiling point range, and any observations about color, clarity, or odor.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
    fumeHoodRequired: false,
    equipmentRequired: ['Graduated cylinder', 'Notebook'],
  },
  {
    id: 'distillation-9',
    title: 'Cool Down and Clean Up',
    description: 'Turn off heat source. Allow apparatus to cool completely. Turn off cooling water. Clean and store equipment properly.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
    fumeHoodRequired: false,
    equipmentRequired: ['Cleaning supplies'],
  },
];

export const distillationExperimentInfo = {
  id: 'simple-distillation',
  name: 'Simple Distillation',
  description: 'Separate a liquid mixture based on differences in boiling points using simple distillation technique.',
  difficulty: 'beginner' as const,
  duration: '30-40 minutes',
  steps: distillationExperiment,
};
