import { ExperimentStep } from './labTrainingSystem';
import { titrationExperimentInfo } from './titrationExperiment';

export const acidBaseNeutralizationExperiment: ExperimentStep[] = [
  {
    id: 'ppe-check',
    title: 'Personal Protective Equipment Check',
    description: 'Put on safety goggles, lab coat, and gloves before beginning the experiment.',
    required: true,
    completed: false,
    safetyCheck: true,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
  },
  {
    id: 'gather-equipment',
    title: 'Gather Required Equipment',
    description: 'Collect beaker, graduated cylinder, stirring rod, and pH indicator.',
    required: true,
    completed: false,
    equipmentRequired: ['beaker', 'graduated_cylinder', 'stirring_rod'],
  },
  {
    id: 'measure-acid',
    title: 'Measure Hydrochloric Acid',
    description: 'Using the graduated cylinder, measure 25 mL of 0.1M HCl solution. Read at eye level to avoid parallax error.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'gloves'],
    fumeHoodRequired: true,
  },
  {
    id: 'transfer-acid',
    title: 'Transfer Acid to Beaker',
    description: 'Carefully pour the measured HCl into a clean 250 mL beaker. Work in the fume hood.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'gloves'],
    fumeHoodRequired: true,
  },
  {
    id: 'add-indicator',
    title: 'Add pH Indicator',
    description: 'Add 2-3 drops of phenolphthalein indicator to the acid solution. Note the color.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'gloves'],
  },
  {
    id: 'measure-base',
    title: 'Measure Sodium Hydroxide',
    description: 'Measure 25 mL of 0.1M NaOH solution in a clean graduated cylinder.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'gloves'],
    fumeHoodRequired: true,
  },
  {
    id: 'titration',
    title: 'Perform Neutralization',
    description: 'Slowly add NaOH to the HCl solution while stirring. Stop when the solution turns pink (pH ~7).',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'gloves'],
  },
  {
    id: 'record-results',
    title: 'Record Observations',
    description: 'Record the volume of NaOH used, final pH, and color change observations.',
    required: true,
    completed: false,
  },
  {
    id: 'cleanup',
    title: 'Clean Up and Dispose',
    description: 'Dispose of neutralized solution in aqueous waste container. Rinse all glassware thoroughly.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'gloves'],
  },
];

export const crystalGrowthExperiment: ExperimentStep[] = [
  {
    id: 'ppe-check',
    title: 'Personal Protective Equipment Check',
    description: 'Put on safety goggles and lab coat.',
    required: true,
    completed: false,
    safetyCheck: true,
    ppeRequired: ['goggles', 'labCoat'],
  },
  {
    id: 'prepare-solution',
    title: 'Prepare Saturated Solution',
    description: 'Heat 100 mL distilled water to 60°C on the hotplate.',
    required: true,
    completed: false,
    ppeRequired: ['goggles'],
  },
  {
    id: 'dissolve-salt',
    title: 'Dissolve Salt',
    description: 'Gradually add salt while stirring until no more dissolves (saturated solution).',
    required: true,
    completed: false,
    ppeRequired: ['goggles'],
  },
  {
    id: 'filter-solution',
    title: 'Filter Solution',
    description: 'Filter the hot solution to remove any undissolved particles.',
    required: true,
    completed: false,
    ppeRequired: ['goggles'],
  },
  {
    id: 'cool-crystallize',
    title: 'Allow Crystallization',
    description: 'Let the solution cool slowly at room temperature. Crystals will form as it cools.',
    required: true,
    completed: false,
  },
  {
    id: 'observe-record',
    title: 'Observe and Record',
    description: 'Observe crystal formation over 24-48 hours. Record crystal shape, size, and growth rate.',
    required: true,
    completed: false,
  },
];

export const qualitativeAnalysisExperiment: ExperimentStep[] = [
  {
    id: 'ppe-check',
    title: 'Personal Protective Equipment Check',
    description: 'Put on safety goggles, lab coat, and gloves.',
    required: true,
    completed: false,
    safetyCheck: true,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
  },
  {
    id: 'prepare-samples',
    title: 'Prepare Test Samples',
    description: 'Transfer small amounts of unknown solutions A and B into separate test tubes.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'gloves'],
  },
  {
    id: 'flame-test',
    title: 'Perform Flame Test',
    description: 'Use a clean wire loop to perform flame tests on each sample. Note the flame color.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'gloves'],
    fumeHoodRequired: true,
  },
  {
    id: 'precipitation-test',
    title: 'Precipitation Test',
    description: 'Add reagents to test for common ions (chloride, sulfate, carbonate). Observe any precipitates.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'gloves'],
  },
  {
    id: 'ph-test',
    title: 'pH Testing',
    description: 'Test the pH of each solution using pH paper or digital pH meter.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'gloves'],
  },
  {
    id: 'identify-compounds',
    title: 'Identify Unknown Compounds',
    description: 'Based on test results, identify the unknown compounds. Record your conclusions.',
    required: true,
    completed: false,
  },
  {
    id: 'waste-disposal',
    title: 'Proper Waste Disposal',
    description: 'Dispose of test solutions in appropriate waste containers based on their chemical properties.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'gloves'],
  },
];

export const allExperiments = {
  'acid-base-titration': titrationExperimentInfo,
  'acid-base-neutralization': {
    name: 'Acid-Base Neutralization',
    description: 'Learn proper titration technique and observe neutralization reactions.',
    difficulty: 'beginner',
    duration: '30 minutes',
    steps: acidBaseNeutralizationExperiment,
  },
  'crystal-growth': {
    name: 'Crystal Growth',
    description: 'Grow crystals from a saturated solution and observe crystallization.',
    difficulty: 'beginner',
    duration: '45 minutes (plus 24-48h observation)',
    steps: crystalGrowthExperiment,
  },
  'qualitative-analysis': {
    name: 'Qualitative Analysis',
    description: 'Identify unknown compounds using chemical tests.',
    difficulty: 'intermediate',
    duration: '45 minutes',
    steps: qualitativeAnalysisExperiment,
  },
};
