import { ExperimentStep } from './labTrainingSystem';
import { titrationExperimentInfo } from './titrationExperiment';
import { distillationExperimentInfo } from './distillationExperiment';

export const acidBaseNeutralizationExperiment: ExperimentStep[] = [
  {
    id: 'ppe-check',
    title: 'Personal Protective Equipment Check',
    description: 'Put on safety goggles, lab coat, and gloves before beginning the experiment.',
    required: true,
    completed: false,
    safetyCheck: true,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
  },
  {
    id: 'gather-equipment',
    title: 'Gather Required Equipment',
    description: 'Collect beaker, graduated cylinder, stirring rod, and pH indicator.',
    required: true,
    completed: false,
    equipmentRequired: ['beaker', 'graduated_cylinder', 'stirring_rod'],
  },
  {
    id: 'measure-acid',
    title: 'Measure Hydrochloric Acid',
    description: 'Using the graduated cylinder, measure 25 mL of 0.1M HCl solution. Read at eye level to avoid parallax error.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'gloves'],
    fumeHoodRequired: true,
  },
  {
    id: 'transfer-acid',
    title: 'Transfer Acid to Beaker',
    description: 'Carefully pour the measured HCl into a clean 250 mL beaker. Work in the fume hood.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'gloves'],
    fumeHoodRequired: true,
  },
  {
    id: 'add-indicator',
    title: 'Add pH Indicator',
    description: 'Add 2-3 drops of phenolphthalein indicator to the acid solution. Note the color.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'gloves'],
  },
  {
    id: 'measure-base',
    title: 'Measure Sodium Hydroxide',
    description: 'Measure 25 mL of 0.1M NaOH solution in a clean graduated cylinder.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'gloves'],
    fumeHoodRequired: true,
  },
  {
    id: 'titration',
    title: 'Perform Neutralization',
    description: 'Slowly add NaOH to the HCl solution while stirring. Stop when the solution turns pink (pH ~7).',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'gloves'],
  },
  {
    id: 'record-results',
    title: 'Record Observations',
    description: 'Record the volume of NaOH used, final pH, and color change observations.',
    required: true,
    completed: false,
  },
  {
    id: 'cleanup',
    title: 'Clean Up and Dispose',
    description: 'Dispose of neutralized solution in aqueous waste container. Rinse all glassware thoroughly.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'gloves'],
  },
];

export const crystalGrowthExperiment: ExperimentStep[] = [
  {
    id: 'ppe-check',
    title: 'Personal Protective Equipment Check',
    description: 'Put on safety goggles and lab coat.',
    required: true,
    completed: false,
    safetyCheck: true,
    ppeRequired: ['goggles', 'labCoat'],
  },
  {
    id: 'prepare-solution',
    title: 'Prepare Saturated Solution',
    description: 'Heat 100 mL distilled water to 60°C on the hotplate.',
    required: true,
    completed: false,
    ppeRequired: ['goggles'],
  },
  {
    id: 'dissolve-salt',
    title: 'Dissolve Salt',
    description: 'Gradually add salt while stirring until no more dissolves (saturated solution).',
    required: true,
    completed: false,
    ppeRequired: ['goggles'],
  },
  {
    id: 'filter-solution',
    title: 'Filter Solution',
    description: 'Filter the hot solution to remove any undissolved particles.',
    required: true,
    completed: false,
    ppeRequired: ['goggles'],
  },
  {
    id: 'cool-crystallize',
    title: 'Allow Crystallization',
    description: 'Let the solution cool slowly at room temperature. Crystals will form as it cools.',
    required: true,
    completed: false,
  },
  {
    id: 'observe-record',
    title: 'Observe and Record',
    description: 'Observe crystal formation over 24-48 hours. Record crystal shape, size, and growth rate.',
    required: true,
    completed: false,
  },
];

export const qualitativeAnalysisExperiment: ExperimentStep[] = [
  {
    id: 'ppe-check',
    title: 'Personal Protective Equipment Check',
    description: 'Put on safety goggles, lab coat, and gloves.',
    required: true,
    completed: false,
    safetyCheck: true,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
  },
  {
    id: 'prepare-samples',
    title: 'Prepare Test Samples',
    description: 'Transfer small amounts of unknown solutions A and B into separate test tubes.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'gloves'],
  },
  {
    id: 'flame-test',
    title: 'Perform Flame Test',
    description: 'Use a clean wire loop to perform flame tests on each sample. Note the flame color.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'gloves'],
    fumeHoodRequired: true,
  },
  {
    id: 'precipitation-test',
    title: 'Precipitation Test',
    description: 'Add reagents to test for common ions (chloride, sulfate, carbonate). Observe any precipitates.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'gloves'],
  },
  {
    id: 'ph-test',
    title: 'pH Testing',
    description: 'Test the pH of each solution using pH paper or digital pH meter.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'gloves'],
  },
  {
    id: 'identify-compounds',
    title: 'Identify Unknown Compounds',
    description: 'Based on test results, identify the unknown compounds. Record your conclusions.',
    required: true,
    completed: false,
  },
  {
    id: 'waste-disposal',
    title: 'Proper Waste Disposal',
    description: 'Dispose of test solutions in appropriate waste containers based on their chemical properties.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'gloves'],
  },
];

export const acidityTestingExperiment: ExperimentStep[] = [
  {
    id: 'acidity-1',
    title: 'Safety Check',
    description: 'Put on safety goggles, lab coat, and gloves before beginning.',
    required: true,
    completed: false,
    safetyCheck: true,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
  },
  {
    id: 'acidity-2',
    title: 'Prepare Test Samples',
    description: 'Gather unknown solutions A, B, and C in separate beakers. Label them clearly.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
    equipmentRequired: ['Beakers', 'Labels'],
  },
  {
    id: 'acidity-3',
    title: 'pH Paper Test',
    description: 'Dip pH paper into each solution. Compare color change with pH chart.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
  },
  {
    id: 'acidity-4',
    title: 'Digital pH Meter',
    description: 'Use digital pH meter for accurate readings. Rinse probe between samples.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
    equipmentRequired: ['pH meter'],
  },
  {
    id: 'acidity-5',
    title: 'Litmus Test',
    description: 'Test with red and blue litmus paper. Record color changes.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
  },
  {
    id: 'acidity-6',
    title: 'Universal Indicator',
    description: 'Add universal indicator drops. Observe and record color.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
  },
  {
    id: 'acidity-7',
    title: 'Record Results',
    description: 'Document pH values and classify each solution as acidic, neutral, or basic.',
    required: true,
    completed: false,
  },
  {
    id: 'acidity-8',
    title: 'Clean Up',
    description: 'Dispose of solutions properly. Rinse all equipment. Remove PPE.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
  },
];

export const chemicalReactionTestExperiment: ExperimentStep[] = [
  {
    id: 'reaction-1',
    title: 'Safety Check',
    description: 'Put on safety goggles, lab coat, and gloves. This reaction produces heat and oxygen gas.',
    required: true,
    completed: false,
    safetyCheck: true,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
  },
  {
    id: 'reaction-2',
    title: 'Prepare Conical Flask',
    description: 'Place a clean 250 mL conical flask on the lab bench.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
    equipmentRequired: ['Conical flask'],
  },
  {
    id: 'reaction-3',
    title: 'Add Hydrogen Peroxide',
    description: 'Carefully measure and pour 50 mL of 3% hydrogen peroxide (H₂O₂) into the flask.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
  },
  {
    id: 'reaction-4',
    title: 'Prepare Potassium Permanganate',
    description: 'Measure 5 mL of 0.1M potassium permanganate (KMnO₄) solution in a graduated cylinder.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
  },
  {
    id: 'reaction-5',
    title: 'Add KMnO₄ to H₂O₂',
    description: 'Slowly add the purple KMnO₄ solution to the H₂O₂ in the flask. AI will analyze the reaction.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
  },
  {
    id: 'reaction-6',
    title: 'Observe Reaction',
    description: 'Watch the color change from purple to colorless. Note bubbling (oxygen gas). AI monitors temperature and gas evolution.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
  },
  {
    id: 'reaction-7',
    title: 'AI Analysis Complete',
    description: 'AI has calculated: Reaction type (Redox), Products (Mn²⁺, O₂, H₂O), Temperature change (+8°C), Gas volume (12 mL O₂).',
    required: true,
    completed: false,
  },
  {
    id: 'reaction-8',
    title: 'Record Results',
    description: 'Document observations: Initial color (purple), Final color (colorless/pale pink), Temperature increase, Gas bubbles.',
    required: true,
    completed: false,
  },
  {
    id: 'reaction-9',
    title: 'Clean Up',
    description: 'Dispose of solution in aqueous waste. Rinse flask thoroughly. Remove PPE.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
  },
];

export const allExperiments = {
  'acid-base-titration': titrationExperimentInfo,
  'acidity-testing': {
    name: 'Acidity Testing',
    description: 'Test and classify unknown solutions as acidic, neutral, or basic using pH indicators and meters.',
    difficulty: 'beginner',
    duration: '20-30 minutes',
    steps: acidityTestingExperiment,
  },
  'chemical-reaction-test': {
    name: 'Chemical Reaction Test',
    description: 'Observe the redox reaction between hydrogen peroxide and potassium permanganate with AI-powered analysis.',
    difficulty: 'beginner',
    duration: '15-20 minutes',
    steps: chemicalReactionTestExperiment,
  },
  'crystal-growth': {
    name: 'Crystal Growth',
    description: 'Grow crystals from a saturated solution and observe crystallization.',
    difficulty: 'beginner',
    duration: '45 minutes (plus 24-48h observation)',
    steps: crystalGrowthExperiment,
  },
  'qualitative-analysis': {
    name: 'Qualitative Analysis',
    description: 'Identify unknown compounds using chemical tests.',
    difficulty: 'intermediate',
    duration: '45 minutes',
    steps: qualitativeAnalysisExperiment,
  },
};
