import { ExperimentStep } from './labTrainingSystem';

export const titrationExperiment: ExperimentStep[] = [
  {
    id: 'titration-1',
    title: 'Safety Check',
    description: 'Put on safety goggles, lab coat, and gloves before starting the titration.',
    required: true,
    completed: false,
    safetyCheck: true,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
    fumeHoodRequired: false,
    equipmentRequired: ['Safety goggles', 'Lab coat', 'Gloves'],
  },
  {
    id: 'titration-2',
    title: 'Prepare Conical Flask',
    description: 'Take the conical flask containing 25.0 mL of HCl solution with phenolphthalein indicator (colorless in acid).',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
    fumeHoodRequired: false,
    equipmentRequired: ['Conical flask', 'HCl solution', 'Phenolphthalein indicator'],
  },
  {
    id: 'titration-3',
    title: 'Fill Burette',
    description: 'Grab the burette filled with 0.1M NaOH solution. Ensure it reads 0.0 mL at the top. The burette is ready to dispense.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
    fumeHoodRequired: false,
    equipmentRequired: ['Burette', 'NaOH solution'],
  },
  {
    id: 'titration-4',
    title: 'Position Flask Under Burette',
    description: 'Place the conical flask directly under the burette tip. Make sure the tip is inside the flask opening.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
    fumeHoodRequired: false,
    equipmentRequired: ['Conical flask', 'Burette'],
  },
  {
    id: 'titration-5',
    title: 'Begin Titration',
    description: 'Grab the burette and SQUEEZE the grip button to open the stopcock. Add NaOH drop by drop. Watch the solution color carefully.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
    fumeHoodRequired: false,
    equipmentRequired: ['Burette', 'Conical flask'],
  },
  {
    id: 'titration-6',
    title: 'Observe Color Change',
    description: 'Continue adding NaOH slowly. The solution will turn from colorless → light pink → pink. Stop when you see a PERSISTENT light pink color (endpoint).',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
    fumeHoodRequired: false,
    equipmentRequired: ['Burette', 'Conical flask'],
  },
  {
    id: 'titration-7',
    title: 'Record Final Volume',
    description: 'Read the final volume on the burette. Calculate the volume of NaOH used (initial - final). Record this measurement.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
    fumeHoodRequired: false,
    equipmentRequired: ['Burette'],
  },
  {
    id: 'titration-8',
    title: 'Calculate Concentration',
    description: 'Use the formula: M₁V₁ = M₂V₂ to calculate the concentration of HCl. Where M₁ = 0.1M (NaOH), V₁ = volume used, V₂ = 25.0 mL (HCl).',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
    fumeHoodRequired: false,
    equipmentRequired: ['Calculator'],
  },
  {
    id: 'titration-9',
    title: 'Clean Up',
    description: 'Dispose of the solution in the aqueous waste container. Rinse the glassware with distilled water. Remove PPE.',
    required: true,
    completed: false,
    ppeRequired: ['goggles', 'labCoat', 'gloves'],
    fumeHoodRequired: false,
    equipmentRequired: ['Waste container', 'Distilled water'],
  },
];

export const titrationExperimentInfo = {
  id: 'acid-base-titration',
  name: 'Acid-Base Titration',
  description: 'Determine the concentration of HCl by titrating with standardized NaOH solution using phenolphthalein indicator.',
  difficulty: 'beginner' as const,
  duration: '20-30 minutes',
  steps: titrationExperiment,
};
